bayesianOptimization:
  dev:
    init_points: 4
    n_iter: 8
    acq: 'ucb'
  prod:
    init_points: 16
    n_iter: 48
    acq: 'ucb'

pbounds:
  reg_alpha: (0.1, 10)
  reg_lambda: (0.1, 10)
  learning_rate: (0.01, 0.1)
  min_child_samples: (2, 10)
  num_leaves: (15, 100)
  min_df: (10, 30)
  k: (128, 512)

features_configuration:
  A:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'lead_time']