bayesianOptimization:
  dev:
    init_points: 4
    n_iter: 8
    acq: 'ucb'
  prod:
    init_points: 16
    n_iter: 48
    acq: 'ucb'

pbounds:
  bagging_fraction: (0.8, 1)
  feature_fraction: (0.6, 1)
  min_child_weight: (0, 22)
  max_depth: (4, 10)
  max_bin: (64, 512)
  bagging_freq: (2, 4)
  min_split_gain: (0,1)
  reg_alpha: (1e-5, 1)
  reg_lambda: (1e-5, 1)
  learning_rate: (0.001, 0.1)  #(0.01, 0.1)
  min_child_samples: (2, 10)
  num_leaves: (15, 108)
  k: (80,512) #(80, 512)

features_configuration:
  A:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price']

  B:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment']

  C:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'lead_time']

  D:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  E:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  F:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  G:
    onehot: [ 'payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform' , 'check_in_month']
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time' ]

  H:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  I:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  J:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  K:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time', 'lead_time_range']

  L:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type', 's_vecation', 'w_vecation']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  M:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type', 'sp_date', 'midd', 'sallery', 'workingday', 'is_rest_day', 'vecation', 'is_event', 's_vecation', 'w_vecation']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time', 'lead_time_range', 'days2vecation', 'vecation_days']

  A1:
    onehot: [ 'payment_type', 'nationality_code', 'gender', 'source', 'currency_code' ]
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price' ]