bayesianOptimization:
  dev:
    init_points: 4
    n_iter: 8
    acq: 'ucb'
  prod:
    init_points: 16
    n_iter: 48
    acq: 'ucb'

pbounds:
  lightgbm:
    reg_alpha: (0.1, 10)
    reg_lambda: (0.1, 10)
    learning_rate: (0.01, 0.1)  #(0.01, 0.1)
    min_child_samples: (2, 10)
    num_leaves: (15, 100)
    #min_df: (10, 30)
    k: (80,512) #(80, 512)   #select k best : 這邊設置的數字較大，所以可能沒有作用。他的做法是，假設我設定80，那我的特徵數處理過後要大於80他才會有起到作用
  logistic_regression:
    C: (0.0001, 10)
    k: (15,100)
    l1_ratio: (0, 1)
  xgboost:
    reg_alpha: (0.1, 10)
    reg_lambda: (0.1, 10)
    learning_rate: (0.01, 0.1)  #(0.01, 0.1)
    min_child_weight: (0, 5)
    max_leaves: (15, 100)
    k: (80,512)



features_configuration:
  A:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price']

  B:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment']

  C:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'lead_time']

  D:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  E:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  F:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time']

  G:
    onehot: [ 'payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform' , 'check_in_month']
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price',  'if_comment', 'lead_time' ]

  H:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  I:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  J:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  K:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time', 'lead_time_range']

  L:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type', 's_vecation', 'w_vecation']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  M:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'currency_code', 'season', 'platform', 'check_in_month','holiday','weekday', 'type', 'sp_date', 'midd', 'sallery', 'workingday', 'is_rest_day', 'vecation', 'is_event', 's_vecation', 'w_vecation']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time', 'lead_time_range', 'days2vecation', 'vecation_days']

  N:
    onehot: [ 'nationality_code', 'gender', 'source', 'season', 'platform' , 'check_in_month']
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'price',  'lead_time' ]

  O:
    onehot: ['nationality_code', 'gender', 'source', 'season', 'platform', 'check_in_month','holiday','weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'price', 'lead_time']

  P:
    onehot: [ 'nationality_code', 'gender', 'source', 'season', 'platform', 'check_in_month','holiday','weekday','midd', 'sallery', 'workingday', 'is_rest_day', 'vecation', 'is_event', 's_vecation', 'w_vecation' ]
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'price', 'lead_time', 'days2vecation', 'vecation_days' ]
